version: 2
jobs:
  build:
    working_directory: ~/gem_uppity
    docker:
      - image: circleci/ruby:2.6.3-node
      environment:
        BUNDLER_VERSION: 2.0.1
    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: gem-uppity-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      - type: cache-save
        name: Store bundle cache
        key: gem-uppity-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Run Rspec specs
          command: bundle exec rspec
